/* Generated by SharpKit 5 v5.4.4 */
if (typeof ($Inherit) == 'undefined') {
	var $Inherit = function (ce, ce2) {

		if (typeof (Object.getOwnPropertyNames) == 'undefined') {

			for (var p in ce2.prototype)
				if (typeof (ce.prototype[p]) == 'undefined' || ce.prototype[p] == Object.prototype[p])
					ce.prototype[p] = ce2.prototype[p];
			for (var p in ce2)
				if (typeof (ce[p]) == 'undefined')
					ce[p] = ce2[p];
			ce.$baseCtor = ce2;

		} else {

			var props = Object.getOwnPropertyNames(ce2.prototype);
			for (var i = 0; i < props.length; i++)
				if (typeof (Object.getOwnPropertyDescriptor(ce.prototype, props[i])) == 'undefined')
					Object.defineProperty(ce.prototype, props[i], Object.getOwnPropertyDescriptor(ce2.prototype, props[i]));

			for (var p in ce2)
				if (typeof (ce[p]) == 'undefined')
					ce[p] = ce2[p];
			ce.$baseCtor = ce2;

		}

	}
};

if (typeof ($CreateAnonymousDelegate) == 'undefined') {
    var $CreateAnonymousDelegate = function (target, func) {
        if (target == null || func == null)
            return func;
        var delegate = function () {
            return func.apply(target, arguments);
        };
        delegate.func = func;
        delegate.target = target;
        delegate.isDelegate = true;
        return delegate;
    }
}

if (typeof($CreateDelegate)=='undefined'){
    if(typeof($iKey)=='undefined') var $iKey = 0;
    if(typeof($pKey)=='undefined') var $pKey = String.fromCharCode(1);
    var $CreateDelegate = function(target, func){
        if (target == null || func == null) 
            return func;
        if(func.target==target && func.func==func)
            return func;
        if (target.$delegateCache == null)
            target.$delegateCache = {};
        if (func.$key == null)
            func.$key = $pKey + String(++$iKey);
        var delegate;
        if(target.$delegateCache!=null)
            delegate = target.$delegateCache[func.$key];
        if (delegate == null){
            delegate = function(){
                return func.apply(target, arguments);
            };
            delegate.func = func;
            delegate.target = target;
            delegate.isDelegate = true;
            if(target.$delegateCache!=null)
                target.$delegateCache[func.$key] = delegate;
        }
        return delegate;
    }
}


var BaseBinder = function (oneway){
    this.inited = false;
    this.oneway = false;
    this.oneway = oneway;
};
BaseBinder.prototype.verifyInit = function (e){
    if (this.inited)
        return;
    this.init(e);
};
BaseBinder.prototype.init = function (e){
    if (this.inited){
        console.log("already inited");
        return;
    }
    this.inited = true;
};
BaseBinder.prototype.databind = function (e){
    this.verifyInit(e);
    var target = $(e.target);
    var source = target.data("source");
    this.onTransfer(source, e.target);
};
BaseBinder.prototype.databindback = function (e){
    if (this.oneway)
        return;
    this.verifyInit(e);
    var target = $(e.target);
    var source = target.data("source");
    this.onTransferBack(source, e.target);
};
BaseBinder.prototype.onTransfer = function (source, target){
};
BaseBinder.prototype.onTransferBack = function (source, target){
};
var BindersContext = function (){
};
BindersContext.prototype.oneway = function (source, target){
    return new PathBinder(source, target, true, null);
};
BindersContext.prototype.onewayonchange = function (source, target){
    return new PathBinder(source, target, true, "change");
};
BindersContext.prototype.twoway = function (source, target){
    return new PathBinder(source, target, false, null);
};
BindersContext.prototype.onchange = function (source, target){
    return new PathBinder(source, target, false, "change");
};
BindersContext.prototype.children = function (source){
    return new ChildrenBinder(source);
};
BindersContext.prototype.toggleclass = function (source, className, oneway, triggers){
    return new ToggleClassBinder(source, className, oneway, triggers);
};
BindersContext.prototype.toggleclassoneway = function (source, className, triggers){
    return new ToggleClassBinder(source, className, true, triggers);
};
var ChildrenBinder = function (sourcePath){
    this.sourcePath = null;
    this.sourcePath = sourcePath;
};
ChildrenBinder.prototype.databind = function (e){
    var target = $(e.target);
    var source = target.data("source");
    ChildrenBinder.bindArrayToChildren(target, null, BindingExt.tryGetByPath(source, this.sourcePath));
};
ChildrenBinder.prototype.databindback = function (e){
};
ChildrenBinder.bindArrayToChildren = function (target, template, source){
    var list = source;
    var el2 = $(target);
    var template2 = $(template);
    if (template2.length == 0)
        template2 = el2.find(".Template:first");
    if (template2.length == 0)
        return;
    if (list == null)
        list = el2.data("source");
    if (!(list instanceof Array))
        return;
    var children = el2.children(":not(.Template)").toArray();
    var createTemplate = function (t){
        return template2.clone(true).removeClass("Template").data("source", t);
    };
    ChildrenBinder.bindArrayToChildrenInternal(list, el2, children, createTemplate);
};
ChildrenBinder.bindArrayToChildrenInternal = function (source, target, children, creator){
    var index = 0;
    var index2 = 0;
    while (index2 < children.length){
        var ch2 = $(children[index2]);
        var dc2 = ch2.data("source");
        if (dc2 == null){
            index2++;
            continue;
        }
        var dc = source[index];
        if (dc != dc2){
            if (dc == null){
                ch2.remove();
                index2++;
                continue;
            }
            else {
                var ch3 = creator(dc);
                ch3.insertBefore(ch2);
                index++;
                continue;
            }
        }
        index2++;
        index++;
    }
    while (index < source.length){
        target.append(creator(source[index]));
        index++;
    }
};
var PropertyBinder = function (source, target, oneway){
    this.sourceProp = null;
    this.targetProp = null;
    BaseBinder.call(this, oneway);
    this.sourceProp = source;
    this.targetProp = target;
    this.oneway = oneway;
};
PropertyBinder.prototype.onTransfer = function (source, target){
    var value = this.sourceProp.get(source);
    this.targetProp.set(target, value);
};
PropertyBinder.prototype.onTransferBack = function (source, target){
    var value = this.targetProp.get(target);
    this.sourceProp.set(source, value);
};
$Inherit(PropertyBinder, BaseBinder);
var PathBinder = function (source, target, oneWay, triggers){
    this.sourcePath = null;
    this.targetPath = null;
    this.triggers = null;
    PropertyBinder.call(this);
    this.sourcePath = source;
    this.targetPath = target;
    this.oneway = oneWay;
    this.triggers = triggers;
};
PathBinder.prototype.init = function (e){
    BaseBinder.prototype.init.call(this, e);
    if (Q.isNullOrEmpty(this.targetPath))
        this.targetPath = PathBinder.getDefaultTargetPath(e.target);
    this.sourceProp = this.createProperty(this.sourcePath);
    this.targetProp = this.createProperty(this.targetPath);
    if (this.triggers != null && this.triggers.length > 0){
        var target = $(e.target);
        target.on(this.triggers, $CreateDelegate(this, this.onTrigger));
    }
};
PathBinder.prototype.createProperty = function (path){
    return {
        get: $CreateAnonymousDelegate(this, function (t){
            return BindingExt.tryGetByPath(t, path);
        }),
        set: $CreateAnonymousDelegate(this, function (t, v){
            Object.trySet(t, path, v);
        })
    };
};
PathBinder.prototype.onTrigger = function (e){
    console.log("Trigger: " + e.type);
    if (this.oneway)
        this.databind(e);
    else
        this.databindback(e);
};
PathBinder.prototype.destroy = function (e){
    if (this.triggers != null && this.triggers.length > 0){
        var target = $(e.target);
        target.off(this.triggers, $CreateDelegate(this, this.databindback));
    }
};
PathBinder.getDefaultTargetPath = function (el){
    if (el.nodeName == "INPUT"){
        if (["radio", "checkbox"].contains(el.type))
            return "checked";
    }
    return "value";
};
$Inherit(PathBinder, PropertyBinder);
if (typeof(CorexJs) == "undefined")
    var CorexJs = {};
if (typeof(CorexJs.DataBinding) == "undefined")
    CorexJs.DataBinding = {};
CorexJs.DataBinding.Plugin = function (){
};
CorexJs.DataBinding.Plugin.databindflat = function (q){
    CorexJs.DataBinding.Plugin.triggerDataBindingEvent(q, "databind", {
        flat: true
    }, "onbind", CorexJs.DataBinding.Plugin.element_databind_default);
    return q;
};
CorexJs.DataBinding.Plugin.databind = function (q){
    CorexJs.DataBinding.Plugin.triggerDataBindingEvent(q, "databind", null, "onbind", CorexJs.DataBinding.Plugin.element_databind_default);
    return q;
};
CorexJs.DataBinding.Plugin.databindback = function (q){
    CorexJs.DataBinding.Plugin.triggerDataBindingEvent(q, "databindback", null, "onbindback", CorexJs.DataBinding.Plugin.element_databindback_default);
    return q;
};
CorexJs.DataBinding.Plugin.addBinder = function (q, binder){
    var binders = CorexJs.DataBinding.Plugin.ProcessAndGetDataAttribute(q, "binders", CorexJs.DataBinding.Plugin.evalBinders);
    if (binders == null){
        binders =  [];
        q.data("binders", binders);
    }
    binders.push(binder);
    return q;
};
CorexJs.DataBinding.Plugin.ProcessAndGetDataAttribute = function (q, name, processor){
    var x = q.data(name);
    if (x == null)
        return null;
    if (typeof(x) == "string"){
        var value = processor(x);
        q.data(name, value);
        return value;
    }
    return x;
};
CorexJs.DataBinding.Plugin.evalBinders = function (code){
    if (!code.contains("return"))
        code = "return " + code;
    var ctx = new BindersContext();
    code = "with(ctx){" + code + "}";
    var func = new Function("ctx", code);
    var res = func.call(null, ctx);
    return res;
};
CorexJs.DataBinding.Plugin.element_setup_default = function (e){
    var target = $(e.target);
    var binders2 = CorexJs.DataBinding.Plugin.ProcessAndGetDataAttribute(target, "bindings", CorexJs.DataBinding.Plugin.parseBindings);
    var binders = CorexJs.DataBinding.Plugin.ProcessAndGetDataAttribute(target, "binders", CorexJs.DataBinding.Plugin.evalBinders);
    if (binders2 != null){
        if (binders == null){
            binders =  [];
            target.data("binders", binders);
        }
        binders.addRange(binders2);
    }
};
CorexJs.DataBinding.Plugin.element_teardown_default = function (e){
    var target = $(e.target);
    var binders = target.data("binders");
    if (binders != null){
        binders.forEach(function (t){
            t.destroy(e);
        });
        target.removeData("binders");
    }
};
CorexJs.DataBinding.Plugin.isinited = function (target){
    return target.data("databind-isinited") === true;
};
CorexJs.DataBinding.Plugin.set_isinited = function (target){
    target.data("databind-isinited", true);
};
CorexJs.DataBinding.Plugin.verifyInit = function (el){
    var target = $(el);
    var isInited = CorexJs.DataBinding.Plugin.isinited(target);
    if (!isInited){
        CorexJs.DataBinding.Plugin.set_isinited(target);
        CorexJs.DataBinding.Plugin.triggerDataBindingEvent(target, "init", null, "oninit", CorexJs.DataBinding.Plugin.element_setup_default);
    }
};
CorexJs.DataBinding.Plugin.element_databind_default = function (e){
    CorexJs.DataBinding.Plugin.verifyInit(e.target);
    var target = $(e.target);
    var dataSource = target.data("source");
    var dataMember = target.data("member");
    var binders = target.data("binders");
    if (binders != null){
        binders.forEach(function (t){
            t.databind(e);
        });
    }
    if (e.flat)
        return;
    var children = target.children(":not(.Template)");
    var childSource = dataSource;
    if (childSource != null && dataMember != null)
        childSource = childSource[dataMember];
    children.toArray().forEach(function (t){
        var t2 = $(t);
        var ctx = t2.data("source");
        if (ctx == null || t2.data("inherited-source") == ctx){
            t2.data("source", childSource);
            t2.data("inherited-source", childSource);
        }
    });
    children.databind();
};
CorexJs.DataBinding.Plugin.element_databindback_default = function (e){
    CorexJs.DataBinding.Plugin.verifyInit(e.target);
    var target = $(e.target);
    var dataSource = target.data("source");
    var binders = target.data("binders");
    if (binders != null)
        binders.forEach(function (t){
            t.databindback(e);
        });
    target.children(":not(.Template)").databindback();
};
CorexJs.DataBinding.Plugin.parseBindings = function (s){
    return null;
};
CorexJs.DataBinding.Plugin.parseStyleAttr = function (s){
    if (s == null || s == "")
        return null;
    var pairs = s.split(";");
    var obj = new Object();
    pairs.forEach(function (pair){
        if (pair == "")
            return;
        var pair2 = pair.split(":");
        obj[pair2[0]] = pair2[1];
    });
    return obj;
};
CorexJs.DataBinding.Plugin.triggerDataBindingEvent = function (q, type, props, attrName, defaultBehavior){
    q.each(function (i, el){
        var ev = new jQuery.Event(type, props);
        CorexJs.DataBinding.Plugin.triggerDataBindingAttrEvent(ev, attrName, el);
        if (ev.isDefaultPrevented())
            return;
        var target = $(el);
        target.triggerHandler(ev);
        if (ev.isDefaultPrevented())
            return;
        defaultBehavior(ev);
    });
};
CorexJs.DataBinding.Plugin.triggerDataBindingAttrEvent = function (e, attrName, el){
    var target = $(el);
    var context = {
        source: target.data("source"),
        member: target.data("member")
    };
    e.target = el;
    CorexJs.DataBinding.Plugin.triggerAttributeEvent(e, attrName, context);
};
CorexJs.DataBinding.Plugin.triggerAttributeEvent = function (e, attrName, globalContext){
    var target = $(e.target);
    var att = target.data(attrName);
    if (att == null)
        return;
    var func = null;
    try{
        func = new Function("event", "context", "with(context){" + att + "}");
    }
    catch(ee){
        console.warn(ee, att);
        return;
    }
    var returnValue = func.call(e.target, e, globalContext);
    if (!e.isDefaultPrevented() && returnValue === false)
        e.preventDefault();
};
var BindingExt = function (){
};
BindingExt.tryGetByPath = function (obj, path){
    if (path == null || path == "")
        return obj;
    return Object.tryGet(obj, path);
};
$.fn.databind = function (){
    return CorexJs.DataBinding.Plugin.databind(this);
};
$.fn.databindflat = function (){
    return CorexJs.DataBinding.Plugin.databindflat(this);
};
$.fn.databindback = function (){
    return CorexJs.DataBinding.Plugin.databindback(this);
};
$.fn.addBinder = function (binder){
    return CorexJs.DataBinding.Plugin.addBinder(this, binder);
};
$.fn.dataparent = function (){
    var source = this.data("source");
    var prev = this;
    var el = this.parent();
    while (el.length > 0){
        if (el.data("source") != source)
            break;
        prev = el;
        el = el.parent();
    }
    return prev;
};
var ToggleClassBinder = function (source, className, oneWay, triggers){
    this.className = null;
    PathBinder.call(this, source, null, oneWay, triggers);
    this.className = className;
};
ToggleClassBinder.prototype.init = function (e){
    PathBinder.prototype.init.call(this, e);
    this.targetProp = {
        get: $CreateAnonymousDelegate(this, function (t){
            return $(t).hasClass(this.className);
        }),
        set: $CreateAnonymousDelegate(this, function (t, v){
            $(t).toggleClass(this.className, v);
        })
    };
};
$Inherit(ToggleClassBinder, PathBinder);

