/* Generated by SharpKit 5 v5.4.4 */
if (typeof($CreateDelegate)=='undefined'){
    if(typeof($iKey)=='undefined') var $iKey = 0;
    if(typeof($pKey)=='undefined') var $pKey = String.fromCharCode(1);
    var $CreateDelegate = function(target, func){
        if (target == null || func == null) 
            return func;
        if(func.target==target && func.func==func)
            return func;
        if (target.$delegateCache == null)
            target.$delegateCache = {};
        if (func.$key == null)
            func.$key = $pKey + String(++$iKey);
        var delegate;
        if(target.$delegateCache!=null)
            delegate = target.$delegateCache[func.$key];
        if (delegate == null){
            delegate = function(){
                return func.apply(target, arguments);
            };
            delegate.func = func;
            delegate.target = target;
            delegate.isDelegate = true;
            if(target.$delegateCache!=null)
                target.$delegateCache[func.$key] = delegate;
        }
        return delegate;
    }
}


if (typeof(CorexJs) == "undefined")
    var CorexJs = {};
if (typeof(CorexJs.DataBinding) == "undefined")
    CorexJs.DataBinding = {};
CorexJs.DataBinding.Binder = function (options){
    this.Options = null;
    this.Options = options;
};
CorexJs.DataBinding.Binder.prototype.init = function (e){
    if (this.Options.TargetPath == null)
        this.Options.TargetPath = CorexJs.DataBinding.Binder.getDefaultTargetPath(e.target);
    if (this.Options.BindBackOn != null && this.Options.BindBackOn.length > 0){
        var target = $(e.target);
        target.on(this.Options.BindBackOn, $CreateDelegate(this, this.databindback));
    }
};
CorexJs.DataBinding.Binder.prototype.databind = function (e){
    var target = $(e.target);
    var source = target.data("source");
    if (this.Options.TargetPath == "children")
        CorexJs.DataBinding.Binder.bindArrayToChildren(target, null, BindingExt.tryGetByPath(source, this.Options.SourcePath));
    else
        CorexJs.DataBinding.Binder.databind_tryCopy(source, this.Options.SourcePath, e.target, this.Options.TargetPath);
};
CorexJs.DataBinding.Binder.prototype.databindback = function (e){
    if (this.Options.OneWay)
        return;
    if (this.Options.TargetPath == "children")
        return;
    var target = $(e.target);
    var source = target.data("source");
    CorexJs.DataBinding.Binder.databind_tryCopy(e.target, this.Options.TargetPath, source, this.Options.SourcePath);
};
CorexJs.DataBinding.Binder.prototype.destroy = function (e){
    if (this.Options.BindBackOn != null && this.Options.BindBackOn.length > 0){
        var target = $(e.target);
        target.off(this.Options.BindBackOn, $CreateDelegate(this, this.databindback));
    }
};
CorexJs.DataBinding.Binder.databind_tryCopy = function (source, sourcePath, target, targetPath){
    var value = BindingExt.tryGetByPath(source, sourcePath);
    Object.trySet(target, targetPath, value);
};
CorexJs.DataBinding.Binder.bindArrayToChildren = function (target, template, source){
    var list = source;
    var el2 = $(target);
    var template2 = $(template);
    if (template2.length == 0)
        template2 = el2.find(".Template:first");
    if (template2.length == 0)
        return;
    if (list == null)
        list = el2.data("source");
    if (!(list instanceof Array))
        return;
    var children = el2.children(":not(.Template)").toArray();
    var createTemplate = function (t){
        return template2.clone(true).removeClass("Template").data("source", t);
    };
    CorexJs.DataBinding.Binder.bindArrayToChildrenInternal(list, el2, children, createTemplate);
};
CorexJs.DataBinding.Binder.bindArrayToChildrenInternal = function (source, target, children, creator){
    var index = 0;
    var index2 = 0;
    while (index2 < children.length){
        var ch2 = $(children[index2]);
        var dc2 = ch2.data("source");
        if (dc2 == null){
            index2++;
            continue;
        }
        var dc = source[index];
        if (dc != dc2){
            if (dc == null){
                ch2.remove();
                index2++;
                continue;
            }
            else {
                var ch3 = creator(dc);
                ch3.insertBefore(ch2);
                index++;
                continue;
            }
        }
        index2++;
        index++;
    }
    while (index < source.length){
        target.append(creator(source[index]));
        index++;
    }
};
CorexJs.DataBinding.Binder.getDefaultTargetPath = function (el){
    if (el.nodeName == "INPUT"){
        if (["radio", "checkbox"].contains(el.type))
            return "checked";
    }
    return "value";
};
CorexJs.DataBinding.Plugin = function (){
};
CorexJs.DataBinding.Plugin.databind = function (q){
    CorexJs.DataBinding.Plugin.triggerDataBindingEvent(q, "databind", "onbind", CorexJs.DataBinding.Plugin.element_databind_default);
    return q;
};
CorexJs.DataBinding.Plugin.databindback = function (q){
    CorexJs.DataBinding.Plugin.triggerDataBindingEvent(q, "databindback", "onbindback", CorexJs.DataBinding.Plugin.element_databindback_default);
    return q;
};
CorexJs.DataBinding.Plugin.element_setup_default = function (e){
    var bindings = CorexJs.DataBinding.Plugin.getBindings(e.target);
    if (bindings != null){
        var binders = bindings.map(function (t){
            return new CorexJs.DataBinding.Binder({
                SourcePath: t.SourcePath,
                TargetPath: t.TargetPath
            });
        });
        var target = $(e.target);
        target.data("_binders", binders);
        binders.forEach(function (t){
            t.init(e);
        });
    }
};
CorexJs.DataBinding.Plugin.element_teardown_default = function (e){
    var target = $(e.target);
    var binders = target.data("_binders");
    if (binders != null){
        binders.forEach(function (t){
            t.destroy(e);
        });
        target.removeData("_binders");
    }
};
CorexJs.DataBinding.Plugin.element_databind_default = function (e){
    var target = $(e.target);
    var dataSource = target.data("source");
    var dataMember = target.data("member");
    var isInited = target.data("databind-isinited") === true;
    if (!isInited)
        CorexJs.DataBinding.Plugin.triggerDataBindingEvent(target, "setup", "onsetup", CorexJs.DataBinding.Plugin.element_setup_default);
    var binders = target.data("_binders");
    if (binders != null){
        binders.forEach(function (t){
            t.databind(e);
        });
    }
    var children = target.children(":not(.Template)");
    var childSource = dataSource;
    if (childSource != null && dataMember != null)
        childSource = childSource[dataMember];
    children.toArray().forEach(function (t){
        var t2 = $(t);
        var ctx = t2.data("source");
        if (ctx == null || t2.data("inherited-source") == ctx){
            t2.data("source", childSource);
            t2.data("inherited-source", childSource);
        }
    });
    children.databind();
};
CorexJs.DataBinding.Plugin.element_databindback_default = function (e){
    var target = $(e.target);
    var dataSource = target.data("source");
    var binders = target.data("_binders");
    if (binders != null){
        binders.forEach(function (t){
            t.databindback(e);
        });
    }
    target.children(":not(.Template)").databindback();
};
CorexJs.DataBinding.Plugin.getBindings = function (el){
    var bindings = CorexJs.DataBinding.Plugin.parseBindings($(el).data("bindings"), null);
    return bindings;
};
CorexJs.DataBinding.Plugin.parseBindings = function (s, defaultTarget){
    if (s == null || s == "")
        return null;
    var pairs = s.split(";");
    var list =  [];
    pairs.forEach(function (pair){
        if (pair == "")
            return;
        var pair2 = pair.split(":");
        var b = {
            SourcePath: pair2[0],
            TargetPath: (pair2[1] != null ? pair2[1] : defaultTarget)
        };
        list.push(b);
    });
    return list;
};
CorexJs.DataBinding.Plugin.triggerDataBindingEvent = function (q, type, attrName, defaultBehavior){
    q.each(function (i, el){
        var ev = new jQuery.Event(type);
        var target = $(el);
        CorexJs.DataBinding.Plugin.triggerDataBindingAttrEvent(ev, attrName, target);
        if (ev.isDefaultPrevented())
            return;
        target.triggerHandler(ev);
        if (ev.isDefaultPrevented())
            return;
        defaultBehavior(ev);
    });
};
CorexJs.DataBinding.Plugin.triggerDataBindingAttrEvent = function (e, attrName, target){
    var source = target.data("source");
    var member = target.data("member");
    CorexJs.DataBinding.Plugin.triggerAttributeEvent(e, attrName, source, member);
};
CorexJs.DataBinding.Plugin.triggerAttributeEvent = function (e, attrName, source, member){
    var att = $(e.target).data(attrName);
    if (att == null)
        return;
    var func = new Function("event", "source", "member", "target", att);
    var returnValue = func.call(e.target, e, source, member, e.target);
    if (!e.isDefaultPrevented() && returnValue === false)
        e.preventDefault();
};
var BindingExt = function (){
};
BindingExt.tryGetByPath = function (obj, path){
    if (path == null || path == "")
        return obj;
    return Object.tryGet(obj, path);
};
$.fn.databind = function (){
    return CorexJs.DataBinding.Plugin.databind(this);
};
$.fn.databindback = function (){
    return CorexJs.DataBinding.Plugin.databindback(this);
};

